---
- name: create user 
  hosts: all
  become : true
  gather_facts: false
  vars_files:
       - users.yml
  tasks:
       - name: create the users and save password
         user:
            name: "{{ item.name }}"
            password: "{{ lookup('password', 'password-' + item.name + ' length=6')| password_hash('sha512') }}"
            uid: "{{ item.uid }}"
            comment: "{{ item.first |capitalize }} {{ item.middle |capitalize }} {{ item.last |capitalize }}"
            state: present
         loop: "{{ myusers }}"
